export enum InterventionState {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  UNDER_INSPECTION = 'UNDER_INSPECTION',
  REJECTED = 'REJECTED',
  CLOSED = 'CLOSED'
}
